#include "PluginEditor.h"
VelvetAudioProcessorEditor::VelvetAudioProcessorEditor(VelvetAudioProcessor& p)
    : AudioProcessorEditor(&p), processorRef(p),
      att_INPUT_GAIN(processorRef.apvts,"INPUT_GAIN",knob_INPUT_GAIN),
      att_GAIN_GAIN_DB_DJ2F(processorRef.apvts,"GAIN_GAIN_DB_DJ2F",knob_GAIN_GAIN_DB_DJ2F),
      att_COMPRESSOR_THRESHOLD_C87U(processorRef.apvts,"COMPRESSOR_THRESHOLD_C87U",knob_COMPRESSOR_THRESHOLD_C87U),
      att_COMPRESSOR_RATIO_C87U(processorRef.apvts,"COMPRESSOR_RATIO_C87U",knob_COMPRESSOR_RATIO_C87U),
      att_COMPRESSOR_ATTACK_C87U(processorRef.apvts,"COMPRESSOR_ATTACK_C87U",knob_COMPRESSOR_ATTACK_C87U),
      att_COMPRESSOR_RELEASE_C87U(processorRef.apvts,"COMPRESSOR_RELEASE_C87U",knob_COMPRESSOR_RELEASE_C87U),
      att_COMPRESSOR_MAKEUP_C87U(processorRef.apvts,"COMPRESSOR_MAKEUP_C87U",knob_COMPRESSOR_MAKEUP_C87U),
      att_REVERB_SIZE_B4W8(processorRef.apvts,"REVERB_SIZE_B4W8",knob_REVERB_SIZE_B4W8),
      att_REVERB_DAMP_B4W8(processorRef.apvts,"REVERB_DAMP_B4W8",knob_REVERB_DAMP_B4W8),
      att_REVERB_MIX_B4W8(processorRef.apvts,"REVERB_MIX_B4W8",knob_REVERB_MIX_B4W8),
      att_BASSBOOSTER_FREQ_0W9Q(processorRef.apvts,"BASSBOOSTER_FREQ_0W9Q",knob_BASSBOOSTER_FREQ_0W9Q),
      att_BASSBOOSTER_GAIN_0W9Q(processorRef.apvts,"BASSBOOSTER_GAIN_0W9Q",knob_BASSBOOSTER_GAIN_0W9Q),
      att_BASSBOOSTER_DRIVE_0W9Q(processorRef.apvts,"BASSBOOSTER_DRIVE_0W9Q",knob_BASSBOOSTER_DRIVE_0W9Q),
      att_BITCRUSHER_BITS_AE6S(processorRef.apvts,"BITCRUSHER_BITS_AE6S",knob_BITCRUSHER_BITS_AE6S),
      att_BITCRUSHER_RATEDIV_AE6S(processorRef.apvts,"BITCRUSHER_RATEDIV_AE6S",knob_BITCRUSHER_RATEDIV_AE6S),
      att_BITCRUSHER_MIX_AE6S(processorRef.apvts,"BITCRUSHER_MIX_AE6S",knob_BITCRUSHER_MIX_AE6S),
      att_STEREOWIDTH_WIDTH_8H5C(processorRef.apvts,"STEREOWIDTH_WIDTH_8H5C",knob_STEREOWIDTH_WIDTH_8H5C),
      att_OUTPUT_GAIN(processorRef.apvts,"OUTPUT_GAIN",knob_OUTPUT_GAIN)
{
    setLookAndFeel(&lnf); setSize(524,616);
    knob_INPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_INPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_INPUT_GAIN.setLookAndFeel(&lnf); knob_INPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_INPUT_GAIN); lbl_INPUT_GAIN.setText("INPUT",juce::dontSendNotification); lbl_INPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_INPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_INPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_INPUT_GAIN);
    knob_GAIN_GAIN_DB_DJ2F.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_GAIN_GAIN_DB_DJ2F.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_GAIN_GAIN_DB_DJ2F.setLookAndFeel(&lnf); knob_GAIN_GAIN_DB_DJ2F.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_GAIN_GAIN_DB_DJ2F); lbl_GAIN_GAIN_DB_DJ2F.setText("GAIN GAIN",juce::dontSendNotification); lbl_GAIN_GAIN_DB_DJ2F.setJustificationType(juce::Justification::centred); lbl_GAIN_GAIN_DB_DJ2F.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_GAIN_GAIN_DB_DJ2F.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_GAIN_GAIN_DB_DJ2F);
    knob_COMPRESSOR_THRESHOLD_C87U.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_THRESHOLD_C87U.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_THRESHOLD_C87U.setLookAndFeel(&lnf); knob_COMPRESSOR_THRESHOLD_C87U.setDoubleClickReturnValue(true,-18.0f); addAndMakeVisible(knob_COMPRESSOR_THRESHOLD_C87U); lbl_COMPRESSOR_THRESHOLD_C87U.setText("COMPRESSOR THRESHOLD",juce::dontSendNotification); lbl_COMPRESSOR_THRESHOLD_C87U.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_THRESHOLD_C87U.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_THRESHOLD_C87U.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_THRESHOLD_C87U);
    knob_COMPRESSOR_RATIO_C87U.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RATIO_C87U.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RATIO_C87U.setLookAndFeel(&lnf); knob_COMPRESSOR_RATIO_C87U.setDoubleClickReturnValue(true,4.0f); addAndMakeVisible(knob_COMPRESSOR_RATIO_C87U); lbl_COMPRESSOR_RATIO_C87U.setText("COMPRESSOR RATIO",juce::dontSendNotification); lbl_COMPRESSOR_RATIO_C87U.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RATIO_C87U.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RATIO_C87U.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RATIO_C87U);
    knob_COMPRESSOR_ATTACK_C87U.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_ATTACK_C87U.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_ATTACK_C87U.setLookAndFeel(&lnf); knob_COMPRESSOR_ATTACK_C87U.setDoubleClickReturnValue(true,10.0f); addAndMakeVisible(knob_COMPRESSOR_ATTACK_C87U); lbl_COMPRESSOR_ATTACK_C87U.setText("COMPRESSOR ATTACK",juce::dontSendNotification); lbl_COMPRESSOR_ATTACK_C87U.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_ATTACK_C87U.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_ATTACK_C87U.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_ATTACK_C87U);
    knob_COMPRESSOR_RELEASE_C87U.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RELEASE_C87U.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RELEASE_C87U.setLookAndFeel(&lnf); knob_COMPRESSOR_RELEASE_C87U.setDoubleClickReturnValue(true,150.0f); addAndMakeVisible(knob_COMPRESSOR_RELEASE_C87U); lbl_COMPRESSOR_RELEASE_C87U.setText("COMPRESSOR RELEASE",juce::dontSendNotification); lbl_COMPRESSOR_RELEASE_C87U.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RELEASE_C87U.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RELEASE_C87U.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RELEASE_C87U);
    knob_COMPRESSOR_MAKEUP_C87U.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_MAKEUP_C87U.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_MAKEUP_C87U.setLookAndFeel(&lnf); knob_COMPRESSOR_MAKEUP_C87U.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_COMPRESSOR_MAKEUP_C87U); lbl_COMPRESSOR_MAKEUP_C87U.setText("COMPRESSOR MAKEUP",juce::dontSendNotification); lbl_COMPRESSOR_MAKEUP_C87U.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_MAKEUP_C87U.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_MAKEUP_C87U.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_MAKEUP_C87U);
    knob_REVERB_SIZE_B4W8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_REVERB_SIZE_B4W8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_REVERB_SIZE_B4W8.setLookAndFeel(&lnf); knob_REVERB_SIZE_B4W8.setDoubleClickReturnValue(true,60.0f); addAndMakeVisible(knob_REVERB_SIZE_B4W8); lbl_REVERB_SIZE_B4W8.setText("REVERB SIZE",juce::dontSendNotification); lbl_REVERB_SIZE_B4W8.setJustificationType(juce::Justification::centred); lbl_REVERB_SIZE_B4W8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_REVERB_SIZE_B4W8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_REVERB_SIZE_B4W8);
    knob_REVERB_DAMP_B4W8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_REVERB_DAMP_B4W8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_REVERB_DAMP_B4W8.setLookAndFeel(&lnf); knob_REVERB_DAMP_B4W8.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_REVERB_DAMP_B4W8); lbl_REVERB_DAMP_B4W8.setText("REVERB DAMPING",juce::dontSendNotification); lbl_REVERB_DAMP_B4W8.setJustificationType(juce::Justification::centred); lbl_REVERB_DAMP_B4W8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_REVERB_DAMP_B4W8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_REVERB_DAMP_B4W8);
    knob_REVERB_MIX_B4W8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_REVERB_MIX_B4W8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_REVERB_MIX_B4W8.setLookAndFeel(&lnf); knob_REVERB_MIX_B4W8.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_REVERB_MIX_B4W8); lbl_REVERB_MIX_B4W8.setText("REVERB MIX",juce::dontSendNotification); lbl_REVERB_MIX_B4W8.setJustificationType(juce::Justification::centred); lbl_REVERB_MIX_B4W8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_REVERB_MIX_B4W8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_REVERB_MIX_B4W8);
    knob_BASSBOOSTER_FREQ_0W9Q.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BASSBOOSTER_FREQ_0W9Q.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BASSBOOSTER_FREQ_0W9Q.setLookAndFeel(&lnf); knob_BASSBOOSTER_FREQ_0W9Q.setDoubleClickReturnValue(true,120.0f); addAndMakeVisible(knob_BASSBOOSTER_FREQ_0W9Q); lbl_BASSBOOSTER_FREQ_0W9Q.setText("BASS BOOST FREQ",juce::dontSendNotification); lbl_BASSBOOSTER_FREQ_0W9Q.setJustificationType(juce::Justification::centred); lbl_BASSBOOSTER_FREQ_0W9Q.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BASSBOOSTER_FREQ_0W9Q.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BASSBOOSTER_FREQ_0W9Q);
    knob_BASSBOOSTER_GAIN_0W9Q.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BASSBOOSTER_GAIN_0W9Q.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BASSBOOSTER_GAIN_0W9Q.setLookAndFeel(&lnf); knob_BASSBOOSTER_GAIN_0W9Q.setDoubleClickReturnValue(true,6.0f); addAndMakeVisible(knob_BASSBOOSTER_GAIN_0W9Q); lbl_BASSBOOSTER_GAIN_0W9Q.setText("BASS BOOST GAIN",juce::dontSendNotification); lbl_BASSBOOSTER_GAIN_0W9Q.setJustificationType(juce::Justification::centred); lbl_BASSBOOSTER_GAIN_0W9Q.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BASSBOOSTER_GAIN_0W9Q.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BASSBOOSTER_GAIN_0W9Q);
    knob_BASSBOOSTER_DRIVE_0W9Q.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BASSBOOSTER_DRIVE_0W9Q.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BASSBOOSTER_DRIVE_0W9Q.setLookAndFeel(&lnf); knob_BASSBOOSTER_DRIVE_0W9Q.setDoubleClickReturnValue(true,20.0f); addAndMakeVisible(knob_BASSBOOSTER_DRIVE_0W9Q); lbl_BASSBOOSTER_DRIVE_0W9Q.setText("BASS BOOST DRIVE",juce::dontSendNotification); lbl_BASSBOOSTER_DRIVE_0W9Q.setJustificationType(juce::Justification::centred); lbl_BASSBOOSTER_DRIVE_0W9Q.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BASSBOOSTER_DRIVE_0W9Q.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BASSBOOSTER_DRIVE_0W9Q);
    knob_BITCRUSHER_BITS_AE6S.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_BITS_AE6S.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_BITS_AE6S.setLookAndFeel(&lnf); knob_BITCRUSHER_BITS_AE6S.setDoubleClickReturnValue(true,8.0f); addAndMakeVisible(knob_BITCRUSHER_BITS_AE6S); lbl_BITCRUSHER_BITS_AE6S.setText("BIT CRUSH BITS",juce::dontSendNotification); lbl_BITCRUSHER_BITS_AE6S.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_BITS_AE6S.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_BITS_AE6S.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_BITS_AE6S);
    knob_BITCRUSHER_RATEDIV_AE6S.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_RATEDIV_AE6S.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_RATEDIV_AE6S.setLookAndFeel(&lnf); knob_BITCRUSHER_RATEDIV_AE6S.setDoubleClickReturnValue(true,4.0f); addAndMakeVisible(knob_BITCRUSHER_RATEDIV_AE6S); lbl_BITCRUSHER_RATEDIV_AE6S.setText("BIT CRUSH RATE DIV",juce::dontSendNotification); lbl_BITCRUSHER_RATEDIV_AE6S.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_RATEDIV_AE6S.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_RATEDIV_AE6S.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_RATEDIV_AE6S);
    knob_BITCRUSHER_MIX_AE6S.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_MIX_AE6S.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_MIX_AE6S.setLookAndFeel(&lnf); knob_BITCRUSHER_MIX_AE6S.setDoubleClickReturnValue(true,80.0f); addAndMakeVisible(knob_BITCRUSHER_MIX_AE6S); lbl_BITCRUSHER_MIX_AE6S.setText("BIT CRUSH MIX",juce::dontSendNotification); lbl_BITCRUSHER_MIX_AE6S.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_MIX_AE6S.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_MIX_AE6S.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_MIX_AE6S);
    knob_STEREOWIDTH_WIDTH_8H5C.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_STEREOWIDTH_WIDTH_8H5C.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_STEREOWIDTH_WIDTH_8H5C.setLookAndFeel(&lnf); knob_STEREOWIDTH_WIDTH_8H5C.setDoubleClickReturnValue(true,120.0f); addAndMakeVisible(knob_STEREOWIDTH_WIDTH_8H5C); lbl_STEREOWIDTH_WIDTH_8H5C.setText("WIDTH WIDTH",juce::dontSendNotification); lbl_STEREOWIDTH_WIDTH_8H5C.setJustificationType(juce::Justification::centred); lbl_STEREOWIDTH_WIDTH_8H5C.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_STEREOWIDTH_WIDTH_8H5C.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_STEREOWIDTH_WIDTH_8H5C);
    knob_OUTPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_OUTPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_OUTPUT_GAIN.setLookAndFeel(&lnf); knob_OUTPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_OUTPUT_GAIN); lbl_OUTPUT_GAIN.setText("OUTPUT",juce::dontSendNotification); lbl_OUTPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_OUTPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_OUTPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_OUTPUT_GAIN);

}
VelvetAudioProcessorEditor::~VelvetAudioProcessorEditor() { setLookAndFeel(nullptr); }
void VelvetAudioProcessorEditor::paint(juce::Graphics& g) {
    g.fillAll(juce::Colour(0xff0d1117));
    g.setColour(juce::Colour(0xff161b22)); g.fillRect(0,0,524,44);
    g.setColour(juce::Colour(0xff4d8bff).withAlpha(0.2f)); g.fillRect(0,43,524,1);
    g.setColour(juce::Colour(0xffe8eaf0).withAlpha(0.4f)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),11.0f,juce::Font::bold));
    g.drawText("VELVET CO",14,0,524-28,44,juce::Justification::centredLeft,false);
    g.setColour(juce::Colour(0xff4d8bff)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),15.0f,juce::Font::bold));
    g.drawText("VELVET",14,0,524-28,44,juce::Justification::centredRight,false);

}
void VelvetAudioProcessorEditor::resized() {
    knob_INPUT_GAIN.setBounds(24,60,112,86); lbl_INPUT_GAIN.setBounds(24,146,120,14);
    knob_GAIN_GAIN_DB_DJ2F.setBounds(144,492,112,86); lbl_GAIN_GAIN_DB_DJ2F.setBounds(144,578,120,14);
    knob_COMPRESSOR_THRESHOLD_C87U.setBounds(24,168,112,86); lbl_COMPRESSOR_THRESHOLD_C87U.setBounds(24,254,120,14);
    knob_COMPRESSOR_RATIO_C87U.setBounds(264,168,112,86); lbl_COMPRESSOR_RATIO_C87U.setBounds(264,254,120,14);
    knob_COMPRESSOR_ATTACK_C87U.setBounds(264,60,112,86); lbl_COMPRESSOR_ATTACK_C87U.setBounds(264,146,120,14);
    knob_COMPRESSOR_RELEASE_C87U.setBounds(384,60,112,86); lbl_COMPRESSOR_RELEASE_C87U.setBounds(384,146,120,14);
    knob_COMPRESSOR_MAKEUP_C87U.setBounds(144,168,112,86); lbl_COMPRESSOR_MAKEUP_C87U.setBounds(144,254,120,14);
    knob_REVERB_SIZE_B4W8.setBounds(384,168,112,86); lbl_REVERB_SIZE_B4W8.setBounds(384,254,120,14);
    knob_REVERB_DAMP_B4W8.setBounds(24,276,112,86); lbl_REVERB_DAMP_B4W8.setBounds(24,362,120,14);
    knob_REVERB_MIX_B4W8.setBounds(144,276,112,86); lbl_REVERB_MIX_B4W8.setBounds(144,362,120,14);
    knob_BASSBOOSTER_FREQ_0W9Q.setBounds(384,276,112,86); lbl_BASSBOOSTER_FREQ_0W9Q.setBounds(384,362,120,14);
    knob_BASSBOOSTER_GAIN_0W9Q.setBounds(264,276,112,86); lbl_BASSBOOSTER_GAIN_0W9Q.setBounds(264,362,120,14);
    knob_BASSBOOSTER_DRIVE_0W9Q.setBounds(24,384,112,86); lbl_BASSBOOSTER_DRIVE_0W9Q.setBounds(24,470,120,14);
    knob_BITCRUSHER_BITS_AE6S.setBounds(144,384,112,86); lbl_BITCRUSHER_BITS_AE6S.setBounds(144,470,120,14);
    knob_BITCRUSHER_RATEDIV_AE6S.setBounds(264,384,112,86); lbl_BITCRUSHER_RATEDIV_AE6S.setBounds(264,470,120,14);
    knob_BITCRUSHER_MIX_AE6S.setBounds(384,384,112,86); lbl_BITCRUSHER_MIX_AE6S.setBounds(384,470,120,14);
    knob_STEREOWIDTH_WIDTH_8H5C.setBounds(24,492,112,86); lbl_STEREOWIDTH_WIDTH_8H5C.setBounds(24,578,120,14);
    knob_OUTPUT_GAIN.setBounds(144,60,112,86); lbl_OUTPUT_GAIN.setBounds(144,146,120,14);
}

